variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

before_script:
  - export AMOLQC=/builds/luechow-group/Amolqc


GNU serial build:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/gnu:11.3.0
  stage: build
  script:
    - ./configure.sh serial_gnu.cmake
    - mkdir -p cmake-build-gnu-serial
    - cd cmake-build-gnu-serial
    - cmake ..
    - make -j 12
  cache:
    key: "$CI_COMMIT_REF_SLUG-gnu-serial"
    paths:
      - cmake-build-gnu-serial/
    policy: pull-push

GNU serial test:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/gnu:11.3.0
  stage: test
  needs: ["GNU serial build"]
  script:
    - cd cmake-build-gnu-serial
    - ctest -E StatisticsTests -L Amolqc --output-on-failure -j 12
  cache:
    key: "$CI_COMMIT_REF_SLUG-gnu-serial"
    paths:
      - cmake-build-gnu-serial/
    policy: pull

GNU parallel build:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/gnu:11.3.0
  stage: build
  script:
  - ./configure.sh openmpi.cmake
  - mkdir -p cmake-build-gnu-parallel
  - cd cmake-build-gnu-parallel
  - cmake ..
  - make -j 12
  cache:
    key: "$CI_COMMIT_REF_SLUG-gnu-parallel"
    paths:
    - cmake-build-gnu-parallel/
    policy: pull-push

GNU parallel test:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/gnu:11.3.0
  stage: test
  needs: ["GNU parallel build"]
  script:
  - cd cmake-build-gnu-parallel
  - ctest -E StatisticsTests -LE serial -L Amolqc --output-on-failure -j 6
  cache:
    key: "$CI_COMMIT_REF_SLUG-gnu-parallel"
    paths:
    - cmake-build-gnu-parallel/
    policy: pull

Intel serial build:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/intel:2021.7.1
  stage: build
  script:
  - . /opt/intel/oneapi/setvars.sh
  - ./configure.sh serial_intel.cmake
  - mkdir -p cmake-build-intel-serial
  - cd cmake-build-intel-serial
  - cmake ..
  - make -j 12
  cache:
    key: "$CI_COMMIT_REF_SLUG-intel-serial"
    paths:
    - cmake-build-intel-serial/
    policy: pull-push

Intel serial test:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/intel:2021.7.1
  stage: test
  needs: ["Intel serial build"]
  script:
  - . /opt/intel/oneapi/setvars.sh
  - cd cmake-build-intel-serial
  - ctest -E StatisticsTests -L Amolqc --output-on-failure -j 12
  cache:
    key: "$CI_COMMIT_REF_SLUG-intel-serial"
    paths:
    - cmake-build-intel-serial/
    policy: pull

#NAG serial build:
#  image: registry.git.rwth-aachen.de/luechow-group/amolqc/nag:7.1
#  stage: build
#  script:
#    - ./configure.sh serial_nag.cmake
#    - mkdir -p cmake-build-nag-serial
#    - cd cmake-build-nag-serial
#    - cmake ..
#    - make -j 12
#  cache:
#    key: "$CI_COMMIT_REF_SLUG-nag-serial"
#    paths:
#      - cmake-build-nag-serial/
#    policy: pull-push
