variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

before_script:
  - export AMOLQC=/builds/luechow-group/Amolqc


GNU serial build:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/gnu:11.2.0
  stage: build
  resource_group: amolqc
  script:
    - ./configure.sh serial_gnu.cmake
    - mkdir -p cmake-build-gnu-serial
    - cd cmake-build-gnu-serial
    - cmake ..
    - make -j12
  cache:
    key: "$CI_COMMIT_REF_SLUG-gnu-serial"
    paths:
      - cmake-build-gnu-serial/
    policy: pull-push

GNU serial std08 build:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/gnu:11.2.0
  stage: build
  resource_group: amolqc
  script:
    - mkdir -p cmake-build-gnu-std08-serial
    - cd cmake-build-gnu-std08-serial
    - cmake -DCONFIG_FILE=OFF -DCMAKE_Fortran_COMPILER=gfortran -DMPI=OFF -DADDITIONAL_FLAGS="-std=f2008" ..
    - make -j12
  cache:
    key: "$CI_COMMIT_REF_SLUG-gnu-std08-serial"
    paths:
      - cmake-build-gnu-std08-serial/
    policy: pull-push

GNU serial test:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/gnu:11.2.0
  stage: test
  resource_group: amolqc
  dependencies:
    - GNU serial build
  script:
    - cd cmake-build-gnu-serial
    - ctest -E StatisticsTests --output-on-failure -j4
  cache:
    key: "$CI_COMMIT_REF_SLUG-gnu-serial"
    paths:
      - cmake-build-gnu-serial/
    policy: pull

GNU parallel build:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/gnu:11.2.0
  stage: build
  resource_group: amolqc
  script:
  - ./configure.sh openmpi_lapack.cmake
  - mkdir -p cmake-build-gnu-parallel
  - cd cmake-build-gnu-parallel
  - cmake ..
  - make -j12
  - chown -R user ../cmake-build-gnu-parallel
  cache:
    key: "$CI_COMMIT_REF_SLUG-gnu-parallel"
    paths:
    - cmake-build-gnu-parallel/
    policy: pull-push

GNU parallel std08 build:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/gnu:11.2.0
  stage: build
  resource_group: amolqc
  script:
    - mkdir -p cmake-build-gnu-std08-parallel
    - cd cmake-build-gnu-std08-parallel
    - cmake -DCONFIG_FILE=OFF -DCMAKE_Fortran_COMPILER=mpifort -DMPI=ON -DADDITIONAL_FLAGS="-std=f2008" ..
    - make -j12
  cache:
    key: "$CI_COMMIT_REF_SLUG-gnu-std08-parallel"
    paths:
      - cmake-build-gnu-std08-parallel/
    policy: pull-push

GNU parallel test:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/gnu:11.2.0
  stage: test
  resource_group: amolqc
  dependencies:
  - GNU parallel build
  script:
  - cd cmake-build-gnu-parallel
  - su user -c "ctest -E StatisticsTests --output-on-failure -j2"
  cache:
    key: "$CI_COMMIT_REF_SLUG-gnu-parallel"
    paths:
    - cmake-build-gnu-parallel/
    policy: pull

Intel serial build:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/intel:2021.7.0
  stage: build
  resource_group: amolqc
  script:
  - source /opt/intel/parallel_studio_xe_2019/psxevars.sh intel64
  - ./configure.sh serial_intel.cmake
  - mkdir -p cmake-build-intel-serial
  - cd cmake-build-intel-serial
  - cmake ..
  - make -j12
  cache:
    key: "$CI_COMMIT_REF_SLUG-intel-serial"
    paths:
    - cmake-build-intel-serial/
    policy: pull-push

Intel serial test:
  image: registry.git.rwth-aachen.de/luechow-group/amolqc/intel:2021.7.0
  stage: test
  resource_group: amolqc
  dependencies:
  - Intel serial build
  script:
  - source /opt/intel/parallel_studio_xe_2019/psxevars.sh intel64
  - cd cmake-build-intel-serial
  - ctest -E StatisticsTests --output-on-failure -j2
  cache:
    key: "$CI_COMMIT_REF_SLUG-intel-serial"
    paths:
    - cmake-build-intel-serial/
    policy: pull
